import Head from "next/head";
import styles from "./mainLayout.module.css";
import Header from "../../../components/Client/Header/Header";
import Footer from "../../../components/Client/Footer/Footer";
import React, { useEffect } from 'react';
import {setUser} from "../../../redux/featuries/user/userSılice";
import { useSelector, useDispatch } from 'react-redux';
const MainLayout = ({children}) => {

    const dispatch = useDispatch();
    useEffect(() => {
        let user = localStorage.getItem("user_info");
        if(user){
            user  = JSON.parse(user);
            if(user) dispatch(setUser(user));
        }
    }, []);
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.main_container}>
                <div className="md:px-8">
                    <Header />
                </div>
                {children}
                <Footer/>
            </div>
        </div>
    );
};

export default MainLayout



