import Head from "next/head";
import styles from "./mainLayout.module.css";
import Header from "../../client/Header/Header";
import Footer from "../../client/Footer/Footer";

const MainLayout = ({children}) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main_container}>
                <Header/>
                {children}
                <Footer/>
            </main>
        </div>
    );
};

export default MainLayout

